### ISSUE TITLE
Make fails in templates/openshift

### ISSUE THREAD

**Issue by spbnick** [BitScoutOrg/elasticsearch-templates#38]
Running `make` in `templates/openshift` aborts with the following output:

```
python ../../scripts/generate_template.py template.yml ../../namespaces/
Traceback (most recent call last):
  File "../../scripts/generate_template.py", line 343, in <module>
    object_types_to_template(template_definition, output, output_index_pattern, args.namespaces_dir)
  File "../../scripts/generate_template.py", line 42, in object_types_to_template
    with open(template_definition['skeleton_index_pattern_path'], 'r') as f:
IOError: [Errno 2] No such file or directory: '../skeleton-index-pattern.json'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by spbnick** [comment]
This still works with commit a4447f9.

**Comment by richm** [comment]
whoops, forgot to commit the new file
To github.com:ViaQ/elasticsearch-templates.git
   f459880..228059c  master -> master

pull and try it again

**Comment by spbnick** [comment]
Indeed, it works now. Thank you, Rich!
